config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show', as: "cart"
  post 'cart/add'
  post 'cart/remove'
  resources :order_details
  resources :orders
  resources :tags
  devise_for :users
  resources :articles
  resources :brands
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :orderables
  has_many :carts, through: :orderables
  belongs_to :brand
  belongs_to :user
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  has_one_attached :image
  has_many_attached :photos
  validate :validar_photos
  
  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end

  private
  def validar_photos
    return if photos.count <= 4

    errors.add(:mensaje, ": Solo puedes subir 4 fotos adicionales")
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :permisos_sobre_articulos?, only: %i[ edit update destroy ]
  
  # GET /articles or /articles.json
  def index
    if params[:tag]
      @articles = Tag.find_by(name: "#{params[:tag]}").articles
    else
      @articles = Article.all
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    @brand = Brand.all
    @article.tags.build
    @tags = Tag.all
  end

  # GET /articles/1/edit
  def edit
    @tags = Tag.all
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    @tags = Tag.all
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
      @brand = Brand.all
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:name, :detail, :price, :image, :brand_id, :user_id, tag_ids: [], tags_attributes: [:id, :name, :_destroy], photos: [])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <% @marca_actual = Brand.find(article.brand_id) %>

  <div class="card mb-2" style="width: 15rem;">

    <% if article.image.attached? %> <%# Imágen Portada %>
      <%= link_to (image_tag article.image, class: "card-img-top"), article %> 
    <% else %>
      <%= link_to (image_tag "ejemplo.jpg", class: "card-img-top"), article %> 
    <% end %>

    <div class="card-body">
      <h5 class="card-title"><%= article.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted">Marca: <%= @marca_actual.name %></h6>
      <p class="card-text"><%= article.detail %></p>
      <p class="card-text">$ <%= article.price %></p>
      <p class="card-subtitle mb-2 text-muted">Vendedor id: <%= article.user_id %></p>
      <p class="card-subtitle mb-2">Etiquetas:</p>

        <% if article.tags.any? %>
          <ul> 
            <% article.tags.each do |q| %>
              <li class="text-muted" >
                <%= q.name %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p class="text-muted" >Sin etiquetas</p>
        <% end %>

    <span>Cantidad a comprar:</span>
    <%= form_with(url: cart_add_path) do |f| %>
      <%= f.hidden_field :id, value: article.id %>
      <%= f.number_field :quantity, style: "max-width: 4rem;", class: "input-group input-group-sm mb-1",  value: 0, min:1 %>
      <%= f.submit "Agregar al Carrito", class: "btn btn-primary btn-sm mb-3" %>
    <% end %>

      <%= link_to "Ver detalles", article, class: "btn btn-outline-primary btn-sm mb-1" %>
    </div>
  </div>
</div>

app/views/articles/_carrusel.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <div id="carouselExampleIndicators" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%# <img src="..." class="d-block w-100" alt="..."> %>
      <%= image_tag "cuna.jpg", class: "d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%# <img src="..." class="d-block w-100" alt="..."> %>
      <%= image_tag "coche.jpg", class: "d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%# <img src="..." class="d-block w-100" alt="..."> %>
      <%= image_tag "mamadera.jpg", class: "d-block w-100" %>
      
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> al guardar:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Nombre:", style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :detail, "Detalles:", class: "mt-2", style: "display: block" %>
    <%= form.text_area :detail %>
  </div>

  <div>
    <%= form.label :brand_id, "Marca:", class: "mt-2", style: "display: block" %>
    <%= form.collection_select :brand_id, @brand, :id, :name %>
  </div>

  <div>
    <%= form.label :price, "Precio:", class: "mt-2", style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <% @var = current_user.try(:id) %>
    <% form.label :user_id, style: "display: block" %>
    <%= form.hidden_field :user_id, value: @var %>
  </div>

  <div>
    <%= form.label :tags, "Categorías:", class: "mt-3", style: "display: block"  %>
    <%= form.collection_check_boxes :tag_ids, @tags, :id, :name  %>
  </div>

    <div>
    <%= form.label :image, "Foto de portada:", style: "display: block", class: "mt-4" %>
    <%= form.file_field :image, accept:'image/jpg,image/png,image/jpeg', style: "display: block", class: "mt-1", required: true %>
  </div>

  <div>
    <%= form.label :photos, "Fotos adicionales (máximo 4):", style: "display: block", class: "mt-4" %>
    <%= form.file_field :photos, multiple: true, accept:'image/jpg,image/png,image/jpeg', style: "display: block", class: "mt-1"%>
  </div>

  <div>
    <%= form.submit "Publicar", class: "btn btn-primary mt-4" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Volver a artículos", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<% if !params[:tag] %>
  <div class="lead mb-5 mt-5" style>
    <h1 class="display-6" >Vende o encuentra todo para tu hijos</h1>
    <p>Los niños crecen rápido y muchas veces te quedas con sus cositas casi nuevas.</p>
    <p>En vendebebe.cl podrás ofrecer todo lo que no uses desde ropita, sillas, juguetes, pañales, etc. y también econtrar lo que necesites ahora para tus hijos. </p>
  </div>

  <%= render "carrusel" %>
<% end %>

<h2 class="mb-4 mt-5">Productos disponibles</h2>
<% if user_signed_in?  %>
  <%= link_to "Ingresar Producto", new_article_path, class: "btn btn-primary mb-3 btn-lg" %>
<% end %>

  <div id="articles">
    <div class="row">
      <% @articles.each do |article| %>
        <div class="col">
            <%= render article %>
        </div>
      <% end %>
    </div>
  </div>

app/views/articles/new.html.erb
<h1>Ingresar producto</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Volver a artículos", articles_path, class: "btn btn-secondary mb-4 btn-sm" %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<% render @article %>

<div class="card mb-3" style="max-width: 50rem;">
  <div class="row g-0">
    <div class="col-md-4">

      <% if @article.image.attached? %> <%# Imágen Portada %>
        <%= link_to (image_tag @article.image, class: "img-fluid rounded-start"), @article %> 
      <% else %>
        <%= link_to (image_tag "ejemplo.jpg", class: "img-fluid rounded-start"), @article %> 
      <% end %>

    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @article.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted">Marca: <%= @marca_actual.name %></h6>
        <p class="card-text"><%= @article.detail %></p>
        <p class="card-text">$ <%= @article.price %></p>
        <p class="card-subtitle mb-2 text-muted">Vendedor id: <%= @article.user_id %></p>
        <p class="card-subtitle mb-2">Etiquetas:</p>

          <% if @article.tags.any? %>
            <ul> 
              <% @article.tags.each do |q| %>
                <li class="text-muted" >
                  <%= q.name %>
                </li>
              <% end %>
            </ul>
          <% else %>
            <p class="text-muted" >Sin etiquetas</p>
          <% end %>

      <span>Cantidad a comprar:</span>
      <%= form_with(url: cart_add_path) do |f| %>
        <%= f.hidden_field :id, value: @article.id %>
        <%= f.number_field :quantity, class: "input-group input-group-sm mb-1", style: "max-width: 4rem;",  value: 0, min:1 %>
        <%= f.submit "Agregar al Carrito", class: "btn btn-primary btn-sm mb-3" %>
      <% end %>

        <%= link_to "Ver detalles", @article, class: "btn btn-outline-primary btn-sm mb-1" %>
      </div>
    </div>
  </div>
</div>

<% if @article.photos.attached? %> <%# Imágenes adjuntas %>
  <div class="row">
    <% @article.photos.each do |foto| %>
      <div class="col">
          <%= link_to image_tag(foto, class: "card col-12"), foto %>
      </div>
    <% end %>
  </div>
<% end %>

<div>
  <% if user_signed_in?  %>
    <%= link_to "Editar este producto", edit_article_path(@article) %> |
    <%= link_to  "Eliminar este producto", @article, method: :delete %>
  <% end %>
  <br>
  <%= link_to "Volver a artículos", articles_path, class: "btn btn-secondary mt-2 btn-sm" %>
</div>